#!/bin/bash
clear
echo 'BTC - 1HgPZvFRKuvsuLXwRtrLsJsws7ivZQScJt'
sleep 5
CONFIG_FILE='dextro.conf'
CONFIGFOLDER='/root/.dextro'
COIN_DAEMON='dextrod'
COIN_CLI='dextro-cli'
COIN_PATH='/usr/local/bin/'
coin_dir='.dextro'
coin_dir2='dextro'
COIN_NAME='Dextro'
COIN_PORT=39320
RPC_PORT=39321
NODEIP=$(curl -s4 icanhazip.com)

PURPLE="\033[0;35m"
RED='\033[0;31m'
GREEN="\033[0;32m"
NC='\033[0m'
MAG='\e[1;35m'

#enter number of additional nodes to create
read -e -p "Enter how many additional nodes you want to setup: " cps
for ((number=1;number <= $cps;number++))
{
if (( $number <= $cps ))
then
cp -r -v -f $CONFIGFOLDER $CONFIGFOLDER$number
cd $CONFIGFOLDER$number
#delete the orignal config
rm $CONFIG_FILE >/dev/null 2>&1
#slide in the new config file
#listen set to 0 - rpcuser and pass randomize
#increase rpcport by $number and prompt for new genkey
RPCUSER=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w10 | head -n1)
RPCPASSWORD=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w22 | head -n1)
echo -e "${GREEN}Creating new config file for $coin_dir$number directory"
read -p "Please enter the next unique GENKEY for this additional masternode: " UNIQUE_GENKEY
read -p "Please enter the IPv6 address you wish to assign to this instance: " NODEIP6
rport=$(($RPC_PORT+$number))
cat > $CONFIG_FILE << EOF
rpcallowip=127.0.0.1
rpcuser=$RPCUSER
rpcpassword=$RPCPASSWORD
rpcport=$rport
staking=1
server=1
listen=0
port=$COIN_PORT masternode=1
masternodeaddr=$NODEIP6:39320
externalip=$NODEIP6:39320
masternodeprivkey=$UNIQUE_GENKEY
addnode=173.212.225.221:39320
addnode=177.152.49.221:39320
addnode=45.63.115.225:39320
EOF
echo -e "${GREEN}$CONFIG_FILE for $coin_dir2$number created with GENKEY=$UNIQUE_GENKEY.${NC}"
rm -rf $coin_dir
cd

#setup new systemctl services for each new node
  cat << EOF > /etc/systemd/system/$COIN_NAME$number.service
[Unit]
Description=$COIN_NAME$number service
After=network.target

[Service]
User=root
Group=root

Type=forking
#PIDFile=$CONFIGFOLDER$number/$COIN_NAME$number.pid

ExecStart=$COIN_PATH$COIN_DAEMON -daemon -conf=$CONFIGFOLDER$number/$CONFIG_FILE -datadir=$CONFIGFOLDER$number
ExecStop=-$COIN_PATH$COIN_CLI -conf=$CONFIGFOLDER$number/$CONFIG_FILE -datadir=$CONFIGFOLDER$number stop

Restart=always
PrivateTmp=true
TimeoutStopSec=60s
TimeoutStartSec=10s
StartLimitInterval=120s
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
EOF

  echo -e "${GREEN}$coin_dir2$number.service created. ${NC}"
  systemctl daemon-reload
  sleep 5
  systemctl start $COIN_NAME$number.service
  systemctl enable $COIN_NAME$number.service >/dev/null 2>&1

  if [[ -z "$(ps axo cmd:100 | egrep $COIN_DAEMON$number)" ]]; then
    echo -e "${RED}$COIN_NAME$number is not running${NC}, please investigate. You should start by running the following commands as root:"
    echo -e "${GREEN}systemctl start $COIN_NAME$number.service"
    echo -e "systemctl status $COIN_NAME#number.service"
    echo -e "less /var/log/syslog${NC}"
    exit 1
  fi
cd
fi
}
clear
echo done
